# **Introduction to NumPy Library**

*Created by Dr. Bayazit Karaman*

*Content adopted from https://numpy.org/doc/stable/user/absolute_beginners.html*

***What is NumPy?***

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

***What is an array?***

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.  It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
import numpy as np

print(np.linspace(0, 10, num=10))

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])

print(a)

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(b)

print(b[0])

print(np.zeros(2))

print(np.ones(3))

print(np.empty(2))

#You can create an array with a range of elements:
print(np.arange(4))

#And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.
print(np.arange(2, 9, 2))

#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
print(np.linspace(0, 10, num=5))

#Specifying your data type to int (default is float)
print(np.ones(2, dtype=np.int64))

[1 2 3]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[0. 0.]
[1. 1. 1.]
[0. 0.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[1 1]


***Adding, removing, and sorting elements***



In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.concatenate((a, b)))

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


***Shape and size of an array***

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

print(array_example.ndim)

print(array_example.size)

print(array_example.shape)

#Reshape of the array
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)

arr2 = arr1.reshape(3, 2)
print(arr2)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
3
24
(3, 2, 4)
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


***How to convert a 1D array into a 2D array?***

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

print(a)

a2 = a[np.newaxis, :]

print(a2)

print(a.ndim)

print(a2.ndim)

#You can also expand an array by inserting a new axis at a specified position with np.expand_dims.
t = np.array([1, 2, 3, 4, 5, 6])
print(t.ndim)

#You can use np.expand_dims to add an axis at index position 1 with:
y = np.expand_dims(t, axis=1)
print(y.ndim)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
1
2
1
2


***Indexing and slicing***

You can index and slice NumPy arrays in the same ways you can slice Python lists.



In [ ]:
data = np.array([1, 2, 3, 4, 5, 6])

print(data[1])

print(data[1:])

print(data[:5])

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

#You can easily print all of the values in the array that are less than 5.
print(a[a < 5])

#You can select elements that satisfy two conditions using the & and | operators:
c = a[(a > 2) & (a < 11)]

print(c)

#You can use np.nonzero() to print the indices of elements that are
b = np.nonzero(a < 5)

print(b)

#If you want to generate a list of coordinates where the elements exist, you can zip the arrays,
#iterate over the list of coordinates, and print them.
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)


2
[2 3 4 5 6]
[1 2 3 4 5]
[1 2 3 4]
[ 3  4  5  6  7  8  9 10]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(0, 0)
(0, 1)
(0, 2)
(0, 3)


***Create an array from existing data***

You can easily create a new array from a section of an existing array. You can create a new array from a section of your array any time by specifying where you want to slice your array.

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

#You can stack them vertically with vstack:
print(np.vstack((a1, a2)))

#Or stack them horizontally with hstack:
print(np.hstack((a1, a2)))

x = np.arange(1, 25).reshape(2, 12)
print(x)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

#we create an array b1 by slicing a and modify the first element of b1.
b1 = a[0, :]
print(b1)

b1[0] = 99
print(b1)

#This will modify the corresponding element in a as well!
print(a)

#Using the copy method will make a complete copy of the array and its data (a deep copy).
b2 = a.copy()

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


***Basic array operations***

Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”. You can add the arrays together with the plus sign.

In [ ]:
data = np.array([1, 2])

ones = np.ones(2, dtype=int)

sum = data + ones

print(sum)

subs = data - ones

print(subs)

mult = data * data

print(mult)

div = data / data

print(div)

#sum
a = np.array([1, 2, 3, 4])

print(a.sum())

b = np.array([[1, 1], [2, 2]])

#You can sum over the axis of rows with:
print(b.sum(axis=0))

#You can sum over the axis of columns with:
print(b.sum(axis=1))

[2 3]
[0 1]
[1 4]
[1. 1.]
10
[3 3]
[2 4]


***Broadcasting***

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes.

In [ ]:
data = np.array([1.0, 2.0])

#NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting.
newData = data * 1.6

print(newData)



[1.6 3.2]


***Matrices***

Indexing and slicing operations are useful when you’re manipulating matrices.

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

print(data[0:2, 0])

print(data.max())

print(data.max(axis=0))

print(data.max(axis=1))

print(data.sum())

print(np.ones((4, 3, 2)))

a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)
print(unique_values)

[[1 2]
 [3 4]
 [5 6]]
[1 3]
6
[5 6]
[2 4 6]
21
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[11 12 13 14 15 16 17 18 19 20]


***Transposing and reshaping a matrix***

It’s common to need to transpose your matrices. NumPy arrays have the property T that allows you to transpose a matrix. You may also need to switch the dimensions of a matrix. This can happen when, for example, you have a model that expects a certain input shape that is different from your dataset. This is where the reshape method can be useful. You simply need to pass in the new dimensions that you want for the matrix.

You can also use .transpose() to reverse or change the axes of an array according to the values you specify.

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6])
print(data)

data1 = data.reshape(2, 3)
print(data1)

data2 = data.reshape(3, 2)
print(data2)

arr = np.arange(6).reshape((2, 3))
print(arr)

arr1 = arr.transpose()
print(arr1)

#Reverse an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

#2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

reversed_arr2d = np.flip(arr_2d)
print('Reversed Array: ', reversed_arr2d)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
Reversed Array:  [8 7 6 5 4 3 2 1]
Reversed Array:  [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
